title: "Torkelsen Tech"
baseurl: "/"
theme: "devcard"
summaryLength: 20
paginate: 6

deployment:
  targets:
    name: azure
    URL: "azblob://$web"

# taxonomies:
#   tag: "tags"
#   category: "categories"
#   publication_type: "publication_types"
#   author: "authors"