title: "Torkelsen Tech"
baseurl: "/"
theme: "devblog"
summaryLength: 30
paginate: 5

mainSections:
- blog

deployment:
  targets:
    name: azure
    URL: "azblob://$web"

# taxonomies:
#   tag: "tags"
#   category: "categories"
#   publication_type: "publication_types"
#   author: "authors"