theme: "theme-tt"

nav:
  description: "Open source enthusiast and freelance consultant with extensive DevOps experience. Loves to explore new technologies."
  image: /img/avatar.png

  contact:
  - icon: "linkedin-in"
    icon_pack: "fab"
    name: "Contact Me"
    link: "https://linkedin.com/in/terjetorkelsen"
  - icon: "github-alt"
    icon_pack: "fab"
    name: "Check code"
    link: "https://github.com/2ttech"

  # button:
  #   link: https://themes.3rdwavemedia.com/
  #   text: Get in Touch