# Build hugo static web site and deploy to Azure Storage account

name: Publish preview

on: push

jobs:
  build-and-publish-draft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.CHECKOUT_PAT  }}

    # Authentication
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}

    # Setup
    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    # Build
    - name: Build hugo
      run: hugo -D -e staging

    # Deploy
    - name: Deploy hugo
      run: hugo deploy
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_DRAFT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY_DRAFT }}
    
    # Purge CDN
    - name: Purge CDN
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az cdn endpoint purge --content-paths /* --ids $AZURE_CDN_RESOURCE_ID
      env:
        AZURE_CDN_RESOURCE_ID: ${{ secrets.AZURE_CDN_RESOURCE_ID_DRAFT }}